apiVersion: v1
kind: Service
metadata:
  name: fastapi-calculator-service
spec:
  type: NodePort
  selector:
    app: fastapi-calculator
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
